-- Generated by pnpm db:generate. Do not edit.
-- Sources: src/server/db/schema.ts and src/server/db/triggers.sql

CREATE TABLE `account` (
	`id` text PRIMARY KEY NOT NULL,
	`user_id` text NOT NULL,
	`account_id` text NOT NULL,
	`provider_id` text NOT NULL,
	`access_token` text,
	`refresh_token` text,
	`id_token` text,
	`access_token_expires_at` integer,
	`refresh_token_expires_at` integer,
	`scope` text,
	`password` text,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE INDEX `account_user` ON `account` (`user_id`);
--> statement-breakpoint
CREATE UNIQUE INDEX `account_provider_identity` ON `account` (`provider_id`,`account_id`);
--> statement-breakpoint
CREATE TABLE `audit_log` (
	`id` text PRIMARY KEY NOT NULL,
	`actor_id` text NOT NULL,
	`subject_id` text NOT NULL,
	`action` text NOT NULL,
	`changed_fields` text,
	`created_at` integer NOT NULL,
	FOREIGN KEY (`actor_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`subject_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE INDEX `audit_log_subject_time` ON `audit_log` (`subject_id`,`created_at`);
--> statement-breakpoint
CREATE TABLE `auth_rate_limit` (
	`key` text PRIMARY KEY NOT NULL,
	`count` integer NOT NULL,
	`expires_at` integer NOT NULL
);
--> statement-breakpoint
CREATE INDEX `auth_rate_limit_expiry` ON `auth_rate_limit` (`expires_at`);
--> statement-breakpoint
CREATE TABLE `event` (
	`id` text PRIMARY KEY NOT NULL,
	`type` text NOT NULL,
	`starts_at` integer NOT NULL,
	`meeting_point` text NOT NULL,
	`meeting_point_url` text,
	`spots` integer NOT NULL,
	`open` integer DEFAULT true NOT NULL,
	`hidden` integer DEFAULT false NOT NULL,
	`cancelled_at` integer,
	`created_by` text NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`created_by`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "event_type" CHECK("event"."type" IN ('patrol', 'orientation')),
	CONSTRAINT "event_positive_spots" CHECK("event"."spots" > 0),
	CONSTRAINT "event_hidden_boolean" CHECK("event"."hidden" IN (0, 1))
);
--> statement-breakpoint
CREATE INDEX `event_starts_at` ON `event` (`starts_at`);
--> statement-breakpoint
CREATE TABLE `event_audit` (
	`id` text PRIMARY KEY NOT NULL,
	`event_id` text NOT NULL,
	`actor_id` text NOT NULL,
	`action` text NOT NULL,
	`changed_fields` text,
	`created_at` integer NOT NULL,
	FOREIGN KEY (`event_id`) REFERENCES `event`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`actor_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE INDEX `event_audit_time` ON `event_audit` (`event_id`,`created_at`);
--> statement-breakpoint
CREATE TABLE `event_notification` (
	`id` text PRIMARY KEY NOT NULL,
	`operation_id` text NOT NULL,
	`user_id` text NOT NULL,
	`subject` text NOT NULL,
	`body` text NOT NULL,
	`delivery_origin` text,
	`status` text DEFAULT 'pending' NOT NULL,
	`attempts` integer DEFAULT 0 NOT NULL,
	`lease_until` integer,
	`created_at` integer NOT NULL,
	`sent_at` integer,
	FOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "event_notification_status" CHECK("event_notification"."status" IN ('pending','sending','sent','local'))
);
--> statement-breakpoint
CREATE INDEX `event_notification_pending` ON `event_notification` (`status`,`created_at`);
--> statement-breakpoint
CREATE INDEX `event_notification_operation` ON `event_notification` (`operation_id`);
--> statement-breakpoint
CREATE TABLE `organizer_bootstrap` (
	`id` integer PRIMARY KEY NOT NULL,
	`user_id` text NOT NULL,
	`created_at` integer NOT NULL,
	FOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "organizer_bootstrap_once" CHECK("organizer_bootstrap"."id" = 1)
);
--> statement-breakpoint
CREATE TABLE `orientation_completion` (
	`id` text PRIMARY KEY NOT NULL,
	`user_id` text NOT NULL,
	`event_id` text NOT NULL,
	`marked_by` text NOT NULL,
	`marked_at` integer NOT NULL,
	FOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`event_id`) REFERENCES `event`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`marked_by`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE UNIQUE INDEX `orientation_completion_user_event` ON `orientation_completion` (`user_id`,`event_id`);
--> statement-breakpoint
CREATE TABLE `profile` (
	`user_id` text PRIMARY KEY NOT NULL,
	`preferred_name` text NOT NULL,
	`pronouns` text,
	`phone` text NOT NULL,
	`birth_date` text NOT NULL,
	`emergency_contact_name` text NOT NULL,
	`emergency_contact_phone` text NOT NULL,
	`emergency_contact_relationship` text NOT NULL,
	`heard_about_us` text NOT NULL,
	`motivation` text NOT NULL,
	`teams` text NOT NULL,
	`medical_certification` text NOT NULL,
	`training_experience` text NOT NULL,
	`medical_conditions` text,
	`registered_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `session` (
	`id` text PRIMARY KEY NOT NULL,
	`user_id` text NOT NULL,
	`token` text NOT NULL,
	`expires_at` integer NOT NULL,
	`ip_address` text,
	`user_agent` text,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`two_factor_verified` integer DEFAULT false NOT NULL,
	FOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE UNIQUE INDEX `session_token_unique` ON `session` (`token`);
--> statement-breakpoint
CREATE INDEX `session_user` ON `session` (`user_id`);
--> statement-breakpoint
CREATE TABLE `signup` (
	`id` text PRIMARY KEY NOT NULL,
	`event_id` text NOT NULL,
	`user_id` text NOT NULL,
	`status` text DEFAULT 'confirmed' NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`event_id`) REFERENCES `event`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "signup_status" CHECK("signup"."status" IN ('confirmed', 'cancelled'))
);
--> statement-breakpoint
CREATE UNIQUE INDEX `signup_one_confirmed_spot` ON `signup` (`event_id`,`user_id`) WHERE "signup"."status" = 'confirmed';
--> statement-breakpoint
CREATE INDEX `signup_event_status` ON `signup` (`event_id`,`status`);
--> statement-breakpoint
CREATE INDEX `signup_user` ON `signup` (`user_id`);
--> statement-breakpoint
CREATE TABLE `two_factor` (
	`id` text PRIMARY KEY NOT NULL,
	`user_id` text NOT NULL,
	`secret` text NOT NULL,
	`backup_codes` text NOT NULL,
	`verified` integer DEFAULT true NOT NULL,
	`failed_verification_count` integer DEFAULT 0 NOT NULL,
	`locked_until` integer,
	FOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE UNIQUE INDEX `two_factor_user_id_unique` ON `two_factor` (`user_id`);
--> statement-breakpoint
CREATE TABLE `user` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`email` text NOT NULL,
	`email_verified` integer DEFAULT false NOT NULL,
	`image` text,
	`role` text DEFAULT 'volunteer' NOT NULL,
	`two_factor_enabled` integer DEFAULT false NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	CONSTRAINT "user_role" CHECK("user"."role" IN ('volunteer', 'organizer'))
);
--> statement-breakpoint
CREATE UNIQUE INDEX `user_email_unique` ON `user` (`email`);
--> statement-breakpoint
CREATE UNIQUE INDEX `user_email_case_insensitive` ON `user` (lower("email"));
--> statement-breakpoint
CREATE TABLE `verification` (
	`id` text PRIMARY KEY NOT NULL,
	`identifier` text NOT NULL,
	`value` text NOT NULL,
	`expires_at` integer NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL
);
--> statement-breakpoint
CREATE INDEX `verification_identifier` ON `verification` (`identifier`);
--> statement-breakpoint
CREATE TABLE `volunteer_status` (
	`user_id` text PRIMARY KEY NOT NULL,
	`active` integer DEFAULT true NOT NULL,
	`patrol_approved` integer DEFAULT false NOT NULL,
	`approved_by` text,
	`approved_at` integer,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`approved_by`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "approval_has_organizer" CHECK("volunteer_status"."patrol_approved" = 0 OR ("volunteer_status"."approved_by" IS NOT NULL AND "volunteer_status"."approved_at" IS NOT NULL))
);
--> statement-breakpoint
-- Current database-enforced business rules. Edit this source, then run pnpm db:generate.
-- Each trigger is one statement; the generator preserves it in a frozen migration.

-- Check eligibility and capacity inside SQLite so concurrent writes cannot overbook.
CREATE TRIGGER signup_confirm_insert
BEFORE INSERT ON signup WHEN NEW.status = 'confirmed'
BEGIN
  SELECT RAISE(ABORT, 'signup_not_eligible')
  WHERE NOT EXISTS (
    SELECT 1 FROM event e
    JOIN volunteer_status v ON v.user_id = NEW.user_id
    JOIN profile p ON p.user_id = v.user_id
    WHERE e.id = NEW.event_id AND e.open = 1 AND v.active = 1
      AND e.starts_at > (julianday('now') - 2440587.5) * 86400000
      AND (e.type = 'orientation' OR v.patrol_approved = 1)
  );
  SELECT RAISE(ABORT, 'event_full')
  WHERE (SELECT count(*) FROM signup WHERE event_id = NEW.event_id AND status = 'confirmed')
    >= (SELECT spots FROM event WHERE id = NEW.event_id);
END;
--> statement-breakpoint
CREATE TRIGGER signup_confirm_update
BEFORE UPDATE OF status, event_id, user_id ON signup WHEN NEW.status = 'confirmed'
BEGIN
  SELECT RAISE(ABORT, 'signup_not_eligible')
  WHERE NOT EXISTS (
    SELECT 1 FROM event e
    JOIN volunteer_status v ON v.user_id = NEW.user_id
    JOIN profile p ON p.user_id = v.user_id
    WHERE e.id = NEW.event_id AND e.open = 1 AND v.active = 1
      AND e.starts_at > (julianday('now') - 2440587.5) * 86400000
      AND (e.type = 'orientation' OR v.patrol_approved = 1)
  );
  SELECT RAISE(ABORT, 'event_full')
  WHERE (SELECT count(*) FROM signup WHERE event_id = NEW.event_id AND status = 'confirmed' AND id != OLD.id)
    >= (SELECT spots FROM event WHERE id = NEW.event_id);
END;
--> statement-breakpoint
CREATE TRIGGER event_capacity_update
BEFORE UPDATE OF spots ON event
BEGIN
  SELECT RAISE(ABORT, 'capacity_below_signups')
  WHERE NEW.spots < (SELECT count(*) FROM signup WHERE event_id = OLD.id AND status = 'confirmed');
END;
--> statement-breakpoint
-- Completion is recorded separately from patrol approval.
CREATE TRIGGER orientation_completion_insert
BEFORE INSERT ON orientation_completion
BEGIN
  SELECT RAISE(ABORT, 'not_an_orientation')
  WHERE NOT EXISTS (SELECT 1 FROM event WHERE id = NEW.event_id AND type = 'orientation');
END;
--> statement-breakpoint
CREATE TRIGGER orientation_completion_update
BEFORE UPDATE OF event_id ON orientation_completion
BEGIN
  SELECT RAISE(ABORT, 'not_an_orientation')
  WHERE NOT EXISTS (SELECT 1 FROM event WHERE id = NEW.event_id AND type = 'orientation');
END;
--> statement-breakpoint
CREATE TRIGGER approval_organizer_insert
BEFORE INSERT ON volunteer_status WHEN NEW.patrol_approved = 1
BEGIN
  SELECT RAISE(ABORT, 'approval_requires_organizer')
  WHERE NOT EXISTS (SELECT 1 FROM user WHERE id = NEW.approved_by AND role = 'organizer');
END;
--> statement-breakpoint
CREATE TRIGGER approval_organizer_update
BEFORE UPDATE OF patrol_approved, approved_by ON volunteer_status WHEN NEW.patrol_approved = 1
BEGIN
  SELECT RAISE(ABORT, 'approval_requires_organizer')
  WHERE NOT EXISTS (SELECT 1 FROM user WHERE id = NEW.approved_by AND role = 'organizer');
END;
--> statement-breakpoint
-- Existing spots survive hiding/closing; new confirmed spots must be visible.
CREATE TRIGGER signup_visible_insert BEFORE INSERT ON signup WHEN NEW.status = 'confirmed'
BEGIN
  SELECT RAISE(ABORT, 'signup_not_eligible') WHERE EXISTS (
    SELECT 1 FROM event WHERE id = NEW.event_id AND (hidden = 1 OR cancelled_at IS NOT NULL)
  );
END;
--> statement-breakpoint
CREATE TRIGGER signup_visible_update BEFORE UPDATE OF status, event_id, user_id ON signup WHEN NEW.status = 'confirmed'
BEGIN
  SELECT RAISE(ABORT, 'signup_not_eligible') WHERE EXISTS (
    SELECT 1 FROM event WHERE id = NEW.event_id AND (hidden = 1 OR cancelled_at IS NOT NULL)
  );
END;
--> statement-breakpoint
-- Preserve at least one active organizer.
CREATE TRIGGER keep_last_organizer BEFORE UPDATE OF role ON user
WHEN OLD.role = 'organizer' AND NEW.role != 'organizer'
BEGIN
  SELECT RAISE(ABORT, 'last_organizer') WHERE (SELECT count(*) FROM user WHERE role = 'organizer') <= 1;
  SELECT RAISE(ABORT, 'last_organizer') WHERE NOT EXISTS (
    SELECT 1 FROM user u JOIN volunteer_status v ON v.user_id=u.id
    WHERE u.id != OLD.id AND u.role='organizer' AND v.active=1
  );
END;
--> statement-breakpoint
CREATE TRIGGER keep_last_active_organizer BEFORE UPDATE OF active ON volunteer_status
WHEN OLD.active = 1 AND NEW.active = 0 AND EXISTS (SELECT 1 FROM user WHERE id = OLD.user_id AND role = 'organizer')
BEGIN
  SELECT RAISE(ABORT, 'last_organizer') WHERE (
    SELECT count(*) FROM user u JOIN volunteer_status v ON v.user_id = u.id WHERE u.role = 'organizer' AND v.active = 1
  ) <= 1;
END;
--> statement-breakpoint
-- One-time organizer bootstrap: verified email and active registration, no mandatory 2FA.
CREATE TRIGGER bootstrap_first_organizer BEFORE INSERT ON organizer_bootstrap
BEGIN
  SELECT RAISE(ABORT, 'organizer_already_exists') WHERE EXISTS (SELECT 1 FROM user WHERE role='organizer');
  SELECT RAISE(ABORT, 'organizer_not_ready') WHERE NOT EXISTS (
    SELECT 1 FROM user u JOIN profile p ON p.user_id=u.id JOIN volunteer_status v ON v.user_id=u.id
    WHERE u.id=NEW.user_id AND u.email_verified=1 AND v.active=1
  );
END;
--> statement-breakpoint
CREATE TRIGGER bootstrap_first_organizer_apply AFTER INSERT ON organizer_bootstrap
BEGIN
  UPDATE user SET role='organizer',updated_at=NEW.created_at WHERE id=NEW.user_id;
  INSERT INTO audit_log(id,actor_id,subject_id,action,changed_fields,created_at)
    VALUES(lower(hex(randomblob(16))),NEW.user_id,NEW.user_id,'role_changed','["role"]',NEW.created_at);
  DELETE FROM session WHERE user_id=NEW.user_id;
END;
