import { createHash } from "node:crypto";
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  writeFileSync,
} from "node:fs";
import { join, resolve } from "node:path";
import { DatabaseSync } from "node:sqlite";
import { fileURLToPath } from "node:url";
import { isDeepStrictEqual, parseArgs } from "node:util";
import { z } from "zod";
import { format } from "prettier";
import {
  generateSQLiteDrizzleJson,
  generateSQLiteMigration,
  type DrizzleSQLiteSnapshotJSON,
} from "drizzle-kit/api";
import config from "../drizzle.config";
import * as databaseSchema from "../src/server/db/schema";

const breakpoint = "\n--> statement-breakpoint\n";
const header =
  "-- Generated by pnpm db:generate. Do not edit.\n" +
  "-- Sources: src/server/db/schema.ts and src/server/db/triggers.sql\n\n";

interface Trigger {
  name: string;
  sql: string;
}
interface RulesSnapshot {
  version: 1;
  triggers: Trigger[];
  sqlHash: string;
}
interface JournalEntry {
  idx: number;
  version: string;
  when: number;
  tag: string;
  breakpoints: boolean;
}
interface Journal {
  version: string;
  dialect: "sqlite";
  entries: JournalEntry[];
}

export function parseTriggers(source: string): Trigger[] {
  const names = new Set<string>();
  return source
    .split("--> statement-breakpoint")
    .map((sql) => sql.trim())
    .filter(Boolean)
    .map((sql) => {
      const declarations = [
        ...sql.matchAll(/^CREATE TRIGGER ([a-z][a-z0-9_]*)\b/gm),
      ];
      if (declarations.length !== 1)
        throw new Error(
          "Each triggers.sql statement must define exactly one named trigger.",
        );
      const name = declarations[0][1];
      if (names.has(name)) throw new Error(`Duplicate trigger: ${name}`);
      names.add(name);
      return { name, sql };
    });
}

export function readDatabaseTriggers() {
  return parseTriggers(
    readFileSync(
      new URL("../src/server/db/triggers.sql", import.meta.url),
      "utf8",
    ),
  );
}

function readJson<T>(path: string): T {
  return JSON.parse(readFileSync(path, "utf8")) as T;
}
async function writeJson(path: string, data: unknown, exclusive = false) {
  writeFileSync(path, await format(JSON.stringify(data), { parser: "json" }), {
    flag: exclusive ? "wx" : "w",
  });
}
function sqlHash(sql: string) {
  return createHash("sha256").update(sql).digest("hex");
}
function schemaContent(snapshot: DrizzleSQLiteSnapshotJSON) {
  const { id: _id, prevId: _prevId, ...content } = snapshot;
  // Drizzle's in-memory snapshots include undefined optional fields; JSON does not.
  return JSON.parse(JSON.stringify(content)) as typeof content;
}

function prepareD1Statements(
  statements: string[],
  previous: DrizzleSQLiteSnapshotJSON,
  current: DrizzleSQLiteSnapshotJSON,
) {
  const { tables } = z
    .object({
      tables: z.record(
        z.string(),
        z.object({
          foreignKeys: z.record(
            z.string(),
            z.object({
              name: z.string(),
              tableTo: z.string(),
              onDelete: z.string().optional(),
            }),
          ),
        }),
      ),
    })
    .parse(previous);
  for (const statement of statements) {
    const table = /^DROP TABLE `([^`]+)`;$/.exec(statement)?.[1];
    if (!table || !current.tables[table]) continue;
    // Deferral does not stop CASCADE/SET NULL actions when SQLite rebuilds a parent.
    for (const child of Object.values(tables)) {
      for (const key of Object.values(child.foreignKeys)) {
        if (
          key.tableTo !== table ||
          !key.onDelete ||
          key.onDelete === "no action"
        )
          continue;
        throw new Error(
          `D1 cannot safely rebuild ${table}: ${key.name} uses ON DELETE ${key.onDelete.toUpperCase()}. Use an explicit data migration or rebuild a non-production database.`,
        );
      }
    }
  }
  // D1 migrations run in transactions: foreign_keys=OFF has no effect there.
  return statements.map((statement) =>
    statement.replace(
      /^PRAGMA foreign_keys=(OFF|ON);$/i,
      (_match, state: string) =>
        `PRAGMA defer_foreign_keys=${state.toUpperCase() === "OFF" ? "ON" : "OFF"};`,
    ),
  );
}

/** All triggers are rebuilt around schema changes, including SQLite table rebuilds. */
export function renderMigration(
  statements: string[],
  previousTriggers: Trigger[],
  triggers: Trigger[],
) {
  return (
    header +
    [
      ...previousTriggers.map(
        ({ name }) => `DROP TRIGGER IF EXISTS "${name}";`,
      ),
      ...statements.map((sql) => sql.trim()),
      ...triggers.map(({ sql }) => sql),
    ].join(breakpoint) +
    "\n"
  );
}

export async function generateDatabaseMigration({
  directory = resolve(config.out ?? "drizzle"),
  schema = databaseSchema,
  triggers = readDatabaseTriggers(),
  name = "database",
  check = false,
}: {
  directory?: string;
  schema?: Record<string, unknown>;
  triggers?: Trigger[];
  name?: string;
  check?: boolean;
} = {}) {
  if (!/^[a-z][a-z0-9_]*$/.test(name))
    throw new Error(
      "Migration names must use lowercase letters, numbers, and underscores.",
    );
  const journalPath = join(directory, "meta", "_journal.json");
  const journal: Journal = existsSync(journalPath)
    ? readJson(journalPath)
    : { version: "7", dialect: "sqlite", entries: [] };
  const migrations: string[] = [];
  let previous: DrizzleSQLiteSnapshotJSON | undefined;
  let previousTriggers: Trigger[] = [];

  // Refuse hand-edited or incomplete output instead of silently accepting it.
  for (const [idx, entry] of journal.entries.entries()) {
    if (entry.idx !== idx)
      throw new Error("Migration journal is out of order.");
    const rules = readJson<RulesSnapshot>(
      join(directory, "meta", `${entry.tag}_rules.json`),
    );
    const sql = readFileSync(join(directory, `${entry.tag}.sql`), "utf8");
    if (rules.version !== 1 || rules.sqlHash !== sqlHash(sql))
      throw new Error(
        `${entry.tag}.sql was edited. Change the source definitions instead.`,
      );
    migrations.push(sql);
    previous = readJson(
      join(directory, "meta", `${String(idx).padStart(4, "0")}_snapshot.json`),
    );
    previousTriggers = rules.triggers;
  }
  const actualFiles = existsSync(directory)
    ? readdirSync(directory)
        .filter((file) => file.endsWith(".sql"))
        .sort()
    : [];
  const expectedFiles = journal.entries.map(({ tag }) => `${tag}.sql`).sort();
  if (!isDeepStrictEqual(actualFiles, expectedFiles))
    throw new Error("Migration SQL files do not match the generated journal.");

  const empty = await generateSQLiteDrizzleJson({});
  empty.id = "00000000-0000-0000-0000-000000000000";
  const current = await generateSQLiteDrizzleJson(
    schema,
    previous?.id ?? empty.id,
  );
  const changed =
    !previous ||
    !isDeepStrictEqual(schemaContent(previous), schemaContent(current)) ||
    !isDeepStrictEqual(previousTriggers, triggers);
  if (check && changed)
    throw new Error("Database definitions changed. Run pnpm db:generate.");

  let sql: string | undefined;
  if (changed) {
    const from = previous ?? empty;
    const statements = prepareD1Statements(
      await generateSQLiteMigration(from, current),
      from,
      current,
    );
    sql = renderMigration(statements, previousTriggers, triggers);
  }

  // Validate the complete history in scratch memory, never against a real D1 binding.
  const db = new DatabaseSync(":memory:");
  try {
    db.exec("PRAGMA foreign_keys = ON");
    for (const migration of [...migrations, ...(sql ? [sql] : [])]) {
      db.exec("BEGIN");
      db.exec(migration);
      db.exec("COMMIT");
    }
  } finally {
    db.close();
  }
  if (!sql) return null;

  const idx = journal.entries.length;
  const prefix = String(idx).padStart(4, "0");
  const tag = `${prefix}_${name}`;
  mkdirSync(join(directory, "meta"), { recursive: true });
  writeFileSync(join(directory, `${tag}.sql`), sql, { flag: "wx" });
  await writeJson(
    join(directory, "meta", `${prefix}_snapshot.json`),
    current,
    true,
  );
  await writeJson(
    join(directory, "meta", `${tag}_rules.json`),
    {
      version: 1,
      triggers,
      sqlHash: sqlHash(sql),
    } satisfies RulesSnapshot,
    true,
  );
  journal.entries.push({
    idx,
    version: current.version,
    when: Math.max(Date.now(), (journal.entries.at(-1)?.when ?? 0) + 1),
    tag,
    breakpoints: true,
  });
  await writeJson(journalPath, journal);
  return `${tag}.sql`;
}

if (
  process.argv[1] &&
  resolve(process.argv[1]) === fileURLToPath(import.meta.url)
) {
  try {
    const { values } = parseArgs({
      options: { check: { type: "boolean" }, name: { type: "string" } },
    });
    const migration = await generateDatabaseMigration(values);
    console.log(
      migration
        ? `Generated drizzle/${migration}`
        : "Database migrations are up to date.",
    );
  } catch (error) {
    console.error(
      error instanceof Error ? error.message : "Database generation failed.",
    );
    process.exitCode = 1;
  }
}
